name: Build static documents

on:
  workflow_dispatch
  push

jobs:
  greeting_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Build static documents"
        run: echo "hello"